services:
  app-container:
    build: .
    ports:
      - "8081:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    stdin_open: true
    tty: true
    privileged: true  # ← ここに追加
